### ISSUE TITLE
Rebuild of Monai Deploy Express

### ISSUE THREAD

**Issue by JHancox** [Project-MONAI/monai-deploy#129]
The working group have decided that a new build of MD Express is needed, which will include builds 0.1.12 of Workflow Manager, 0.1.10 of Task Manager and 0.3.17 of Monai Informatics Gateway.

**Comment by JHancox** [comment]
Here is a summary of the changes to the config files that need reconciling before I make a PR. All clarification welcome!

- Is the `OpenID` section in the appsettings.json files optional for MDE or redundant?
- In MDE, references to 'localhost' seem to not work. instead, 'rabbitmq', 'mongodb' or 'minio' need to be specified. Is this expected?
- Is Kestrel superseding previous logging systems? Looks like it's not used by mdl-tm yet, but is by mdl-ig & mdl-wm - right?

**K8s Task-Manager (0.1.10) appsettings.json:**

- The following 4 entries are not present. Are they no longer needed or do they need to be retained for MDExpress?:

```
"WorkloadManagerDatabase": {
    ...
    "WorkflowCollectionName": "Workflows",
    "WorkflowInstanceCollectionName": "WorkflowInstances",
    "PayloadCollectionName": "Payloads",
    "TaskDispatchEventCollectionName": "TaskDispatchEvents"
```

- In the MDE version below the "retryDelays" value is set to "5" - Is this correct?

```
"messaging": {
      "retries": {
        "retryDelays": "localhost"
      },
```

- In MDE, apart from "localhost:9000" being "minio:9000", "minioadmin" is used as the value for both "accessKey" and "accessToken" 

```
"storage": {
      "serviceAssemblyName": "Monai.Deploy.Storage.MinIO.MinIoStorageService, Monai.Deploy.Storage.MinIO",
      "settings": {
        "endpoint": "localhost:9000",
        "accessKey": "admin",
        "accessToken": "password",
```

**K8s Workload-Manager (0.1.10) appsettings.json:**

- Same entry for "WorkloadManagerDatabase" as per Task-Manager above

- In MDE version of below, "bucket" is set to "monaideploy:

```
"storage": {
      ...
      "settings": {
	...
       "bucket": "test-bucket"
```

- In the MDE version "Url" is set to "http://+:5000"

```
"Kestrel": {
    "EndPoints": {
      "Http": {
        "Url": "http://localhost:5000"
```

**K8s Informatics-Gateway (0.3.17)**

- set to true in MDE version:

```
"MonaiDeployAuthentication": {
    "bypassAuthentication": false
```

- In MDE it sets a mongodb connection, rather than the sqllite one below. Is this a difference in design between the two or an impending move to sqllite?

```
"ConnectionStrings": {
    "Type": "Sqlite",
    "InformaticsGatewayDatabase": "Data Source=/database/mig.db"
  }
```

- "rejectUnknownSources" is set to false in MDE.

```
"InformaticsGateway": {
    "dicom": {
      ...
        "rejectUnknownSources": true
```

- For messaging/subscriberSettings and publisherSettings MDE uses "admin" for these:

```
"username": "username",
"password": "password",
```

- Like Task-Manager above, in MDE, apart from "minioadmin" is used as the value for both "accessKey" and "accessToken". 
Also "executableLocation": "mc", rather than "/bin/mc" (I guess its pathed anyhow).

**Comment by mocsharp** [comment]
BTW, WM has been updated to v0.1.12

**Comment by mocsharp** [comment]
> The following 4 entries are not present. Are they no longer needed or do they need to be retained for MDExpress?:

Not sure about this one but would guess it's no longer needed if it's not in the [appsettings.json](https://github.com/Project-MONAI/monai-deploy-workflow-manager/blob/develop/src/WorkflowManager/WorkflowManager/appsettings.json) file.

@neildsouth Could you please confirm? Thanks

**Comment by neildsouth** [comment]
re:

> The following 4 entries are not present. Are they no longer needed or do they need to be retained for MDExpress?:

these aren't used and can be discarded.
the collection names look to be fixed in code.
