### ISSUE TITLE
MONAI Deploy Express Workflow Manager http://localhost:5001/ gives HTTP ERROR 404

### ISSUE THREAD

**Issue by justinhorton2003** [Project-MONAI/monai-deploy#133]
I am happy to provide more context. My issue is that it seems the Workflow Manager and Task Manager aren't working and I can't test out sample workflows. The curl command provided in the documentation doesn't return a workflow ID.

**Comment by justinhorton2003** [comment]
> Hi @justinhorton2003  this is expected as the Workflow Manager doesn't host any content at the root. 

Thank you for the info, I am a bit of a novice so bear with me and please ask for clarification if needed. I have MONAI Deploy Express composed up and running but I can't define and run a workflow per what the documentation of Deploy Express says (with Curl command, doesn't return Workflow Id). I can access things like RabbitMQ and such, but I don't fully understand the relationship between the already running Workflow Manager subcontainer of Deploy Express and the whole separate MONAI Workflow Manager repository. I follow the instructions on the Workflow Manager repository and dotnet build/run after cloning into my WSL Ubuntu machine but still no luck. My question is how do I integrate the separate Workflow Manager repo, should I even be doing that? What about the Informatics Gateway? Let me know if you have more questions. I've followed the documentation but I feel like I'm missing something apparent.

**Comment by mocsharp** [comment]
We have just released an update @ https://github.com/Project-MONAI/monai-deploy/releases/tag/monai-deploy-express-v0.4.0

It fixed the issue you described above. Please give it a try and let us know!

Thanks!

**Comment by justinhorton2003** [comment]
Thank you! I did the sample hello-world workflow and it returned an Id. I also tested the Liver Segmentation workflow, although I'm slightly confused. To test it out should I send all 588 files (the whole folder) from the Abdomen Dataset to Dicom Modality or only one specific instance in Orthanc? Also, could you tell me where the separate Workflow Manager repository comes into play? Where should I clone the repository (same question for the Informatics Gateway too) and follow its documentation (dotnet build and run)? How do I integrate it and what does it do? Since it returned the Workflow Id and executed tasks without me having the separate Workflow Manager. Thank you so much for the timely help.

**Comment by mocsharp** [comment]
Hi @justinhorton2003 , you must send all 588 instances to Orthanc for the AI model to work. 

Are you planning to modify or contribute to Informatics Gateway or Workflow Manager? If not, you do not need to clone the source code. Links below in case you need them.

[Informatic Gateway](https://github.com/Project-MONAI/monai-deploy-informatics-gateway)
[Workflow Manager](https://github.com/Project-MONAI/monai-deploy-workflow-manager)

**Comment by justinhorton2003** [comment]
I'm not currently planning on doing that but in theory, how would I connect those services if I did wish to modify them? Also, how would I get the Informatics Gateway UI to work by default (with Deploy Express) since when I go to the specified port 5000 it returns this "No webpage was found for the web address: http://localhost:5000/ HTTP ERROR 404"? Again thank you for such speedy and helpful responses.

**Comment by mocsharp** [comment]
If you modify any of these services, all you need to do is build the docker image(s) and then update the `.env` file in the MONAI Deploy Express package with the locally built image(s) name.

Sorry to inform you that there is no UI associated with these services at this time.

**Comment by justinhorton2003** [comment]
Thank you for all the information and for being so helpful. I'll close the issue now. Have a nice day.
