### ISSUE TITLE
Remove deployed workflow definition from MONAI Deploy Workflow Manager

### ISSUE THREAD

**Issue by SameerShanbhogue** [Project-MONAI/monai-deploy#146]
Hi 

Is there a way to remove deployed workflow definition from MONAI Deploy Workflow Manager.? like using curl --request DELETE

**Comment by mocsharp** [comment]
Yes. 

First, get a list of all installed workflows

```
curl --location 'http://localhost:[port]/workflows'
```

Find the `workflow_id` that you want to delete with the following API call:

```
curl --location --request DELETE 'http://localhost:[port]/workflows/[workflow_id]'
```

**Comment by SameerShanbhogue** [comment]
@mocsharp Thanks, it works.

**Comment by mocsharp** [comment]
Closing as resolve.
