### ISSUE TITLE
Create a Methods Paper based on the MONAI Workloads Document

### ISSUE THREAD

**Issue by slbryson** [Project-MONAI/monai-deploy#48]
The MONAI Deploy Working group believes there is benefit in using the information collected in the MONAI Workloads document to help _evangelize_ the motivating factors found in the MONAI Deploy working group around clinical workflows and how they map to AI deployment workloads.

**Comment by hshuaib90** [comment]
See draft here: https://docs.google.com/document/d/1nRoFwAzudb1rVKv1OC6DWjbE1iQuYNiXk5SykHHu8Oo/edit#heading=h.z8j1zqas0foi

Is it ok for this to be in Google Doc? Happy to convert to Markdown.

**Comment by slbryson** [comment]
Let's edit on it with Google Docs for a while longer and then we can convert it prior to publishing here in the repo if necessary.  I suspect we will need to be prepared to be flexible with base format to get it into various publications.

**Comment by slbryson** [comment]
Action Item from previous meeting to create some terminology: The document has a few definitions:

- Clinical Use Case: Defines the high level clinical use case where AI could be helpful. Example: Emergency brain hemorrhage diagnosis
- Clinical Workflow: Defines the clinical workflow including the systems, data types and response times that describe the next level of detail for each clinical use case.
- 
- Computational Workload: Compute workload types for managing and processing Clinical Workloads.

- Asynchronous Computational Workload
- Asynchronous Result Computational Workload
- Batch Computational Workload
- Streaming Computational Workload
- Synchronous Computational Workload
We can add other terminology as needed.
Are there other terms we need to define in the document to ensure Clinicians as well as IT professionals can follow the workflows?

**Comment by GreySeaWolf** [comment]
We may need an  "I do not know/Info not available" option for non-technical/clinical survey-takers who may not know the details and\or the answers to some of the technical questions

**Comment by dbericat** [comment]
Approved from my end! :)
