### ISSUE TITLE
MD Express – Hello World example – no file list output

### ISSUE THREAD

**Issue by tomaroberts** [Project-MONAI/monai-deploy#90]
Hi all,

Further to conversation in Slack, I've deployed MDE on a Windows 10 machine running WSL2. The containers are up, running and healthy. 

I am testing the [Hello World example here](https://github.com/Project-MONAI/monai-deploy/tree/main/deploy/monai-deploy-express#hello-world). I can access Orthanc and upload data (I'm using the LN00014 liver CT test dataset provided in the instructions).

I am returned a `workflow_id` when I POST a workflow definition.

I can run a job, which appears to be successful:

![image](https://user-images.githubusercontent.com/15610752/196191452-6e5c5325-ff64-48b6-a37c-2520f72fb5d9.png)

However, when I view the alpine Docker logs, I'm not seeing the output file list. Instead I get this:

![image](https://user-images.githubusercontent.com/15610752/196193003-9c5124d3-e842-4e2f-a8b2-bcb539631e91.png)

Any help much appreciated. Let me know if you need any more info.

PS: I've also tried running the Liver Seg MAP example, which again says Success in the Orthanc jobs page, but I'm not getting any output.

**Comment by mocsharp** [comment]
@tomaroberts the logs you've shared above were from the container that sets up MIG with AE Titles.

Were there any other containers? You may run the following to get all containers

```
docker container list -a
```

**Comment by tomaroberts** [comment]
Thanks Victor – see below:

![image](https://user-images.githubusercontent.com/15610752/196386192-542eee9b-6737-4f49-838a-a9e09e68eca3.png)

**Comment by mocsharp** [comment]
It doesn't look like it triggered any workflows.  Would you be able to capture any logs from the services?

```bash
docker compose logs # all logs from all services
docker logs mdl-ig # logs from Informatics Gateway
docker logs mdl-wm # logs from workflow manager
docker logs mdl-tm # logs from task manager
```

**Comment by tomaroberts** [comment]
Sure. Here's my workflow:

- `docker compose up`
- `curl ... `, which gives:
<img width="860" alt="image" src="https://user-images.githubusercontent.com/15610752/196664545-feb85f69-aeaa-42ed-b869-076f47038f19.png">

- Goto Orthanc, send a single (instance) DICOM file to MONAI Deploy

Here are the logs (sorry, a lot of chaff in these as forgot to docker compose down):
[docker_compose_logs.txt](https://github.com/Project-MONAI/monai-deploy/files/9819663/docker_compose_logs.txt)
[mdl-ig_logs.txt](https://github.com/Project-MONAI/monai-deploy/files/9819665/mdl-ig_logs.txt)
[mdl-wm_logs.txt](https://github.com/Project-MONAI/monai-deploy/files/9819671/mdl-wm_logs.txt)
[mdl-tm_logs.txt](https://github.com/Project-MONAI/monai-deploy/files/9819670/mdl-tm_logs.txt)

Ok, so when I ran `docker logs mdl-tm`, it threw a bunch of exceptions relating to Rabbit:

![tm-exceptions](https://user-images.githubusercontent.com/15610752/196669485-faf08d2b-1543-474a-a9e3-915773ce3b8b.JPG)

**Comment by mocsharp** [comment]
Here's what I've found in TM's log:
```
[08:56:45 ERR] Error deploying Container.
Docker.DotNet.DockerApiException: Docker API responded with status code=BadRequest, response={"message":"Unknown runtime specified nvidia"}

   at Docker.DotNet.DockerClient.HandleIfErrorResponseAsync(HttpStatusCode statusCode, HttpResponseMessage response, IEnumerable`1 handlers)
   at Docker.DotNet.DockerClient.MakeRequestAsync(IEnumerable`1 errorHandlers, HttpMethod method, String path, IQueryString queryString, IRequestContent body, IDictionary`2 headers, TimeSpan timeout, CancellationToken token)
   at Docker.DotNet.ContainerOperations.CreateContainerAsync(CreateContainerParameters parameters, CancellationToken cancellationToken)
   at Monai.Deploy.WorkflowManager.TaskManager.Docker.DockerPlugin.ExecuteTask(CancellationToken cancellationToken) in /app/src/TaskManager/Plug-ins/Docker/DockerPlugin.cs:line 154
```

The Docker daemon may not be configured to use NVIDIA container runtime and, therefore unable to start the containers.  Please refer to the *Enable NVIDIA Container Runtime for Docker* section in the [README](https://github.com/Project-MONAI/monai-deploy/tree/main/deploy/monai-deploy-express#enable-nvidia-container-runtime-for-docker) and ensure that NVIDIA driver is installed.

**Comment by tomaroberts** [comment]
@mocsharp – working now, thanks!

I remember seeing that part in the README when I first read through it, but didn't implement the Docker Engine changes at the time, naively thinking it wouldn't matter for the Hello World example. Suggest promoting and making more prominent under the Docker Desktop bullet point [in the README](https://github.com/Project-MONAI/monai-deploy/tree/main/deploy/monai-deploy-express#windows-subsystem-for-linux-v2).

**Comment by dbericat** [comment]
Great troubleshooting! @tomaroberts you got this! Create a PR with the changes for the README where you think it's best and ask Victor and myself to review. 

Gotta 'upgrade' you from advanced user to 'committer'. Ha! :)

**Comment by JHancox** [comment]
Closing - since the docs have been updated
